### ISSUE TITLE
The little girl at home page really scares me

### ISSUE THREAD

**Issue by LitoNeo** [ryan-brazeal-ufl/OpenPyLivox#1]
I notice at the README that it offers some funcions that LIVOX_VIEWER does, so I wonder if there is a method or API that I can use to handle .lvx files?

BTW, thanks for this awesome project, it's really helpful !
ewwww, yeah and I am still scared and it would be a long night tonight.....

**Comment by ryan-brazeal-ufl** [comment]
Are you wanting for OpenPyLivox to be able to create a .LVX file? For playback/usage within the Livox-Viewer? I am aware of the Livox documentation on their LVX format and will gladly add support for creating LVX files as an output from OpenPyLivox. In an upcoming release there will be support for the ASPRS .LAS v1.2 file format.

**Comment by LitoNeo** [comment]
Yes，thanks！

**Comment by ryan-brazeal-ufl** [comment]
Hello,
OpenPyLivox (OPL) has just been updated to v1.1.0 and now fully supports the Livox Horizon sensor. A fellow developer has expressed interest in contributing an LVX reader to OPL, stay tuned for updates.
All the best,
-RB
