### ISSUE TITLE
Problem in the data packages' DATA_TYPE

### ISSUE THREAD

**Issue by roya-correct-ai** [ryan-brazeal-ufl/OpenPyLivox#11]
Hi Ryan

Hope you are well.
As it is mentioned in the Livox lidar communication protocol, the data_type for Horizon is equal to 2 and for IMU data is equal to 6. the lidar can send the XYZ data package also IMU data package together. When I run the official Livox-SDK in c++, between a bunch of XYZ data packages with data_type=2 there is a data package with data_type=6 related to IMU data. 
But when I run the OpenPyLivox library, it always gives me data_type=2. 
could you please let me know what is the problem? I only run the code and let it capture data. 
I know the current library does not support Horizon and IMU data, but at least I have to see the data_type=6 in the output because it is something related to data packages, not the code. 
Which part I have to change to have both data-types? is it something related to the socket()?
I do appreciate if you guide me with this issue. 

Many thanks in advance

For example, Here is an output from official Livox-SDK. we can see data-type equal to 6 between others.
 
Thanks

![data type](https://user-images.githubusercontent.com/62161828/88861004-4336ab80-d1ba-11ea-9ae6-e4c3f84d580d.png)

**Comment by ryan-brazeal-ufl** [comment]
Hello,
My apologies for the delay, but OpenPyLivox (OPL) has just been updated to v1.1.0 and now fully supports the Livox Horizon sensor, including IMU data. Please check it out and report back any new issues, bugs, etc. There are still lots of upcoming features for OPL and hopefully, it won't take as long to get them implemented, tested, and released.
All the best,
-RB
