### ISSUE TITLE
Whether Livox-Horizon can run OpenPyLivox or not

### ISSUE THREAD

**Issue by 757628** [ryan-brazeal-ufl/OpenPyLivox#12]
I have a Livox-Horizon lidar and want to use python to take the point cloud data,can this code run on Livox-Horizon ?

**Comment by ryan-brazeal-ufl** [comment]
Hello,
OpenPyLivox (OPL) has just been updated to v1.1.0 and now fully supports the Livox Horizon sensor.
All the best,
-RB
