### ISSUE TITLE
 Applying lidarSpinUp function after lidarSpinDown

### ISSUE THREAD

**Issue by Vldub** [ryan-brazeal-ufl/OpenPyLivox#14]
Hi Ryan
Unable to wake up lidar from power saving mode. Lidar model Horizon.
Please tell me what is the problem?

**Comment by ryan-brazeal-ufl** [comment]
Hello,
Can you please succinctly explain the steps you are performing which is causing the sensor to go into power-saving mode and also the steps you are attempting afterward that do not seem to be working?
Thanks,
Ryan
