### ISSUE TITLE
Firmware upgrade

### ISSUE THREAD

**Issue by mikeszabi** [ryan-brazeal-ufl/OpenPyLivox#21]
Hi, is there a way to do a firmware upgrade through openpylivox?

**Comment by ryan-brazeal-ufl** [comment]
Hello,
OPL does not support applying a firmware update to a sensor. This is only because the Livox SDK does not document how to perform this operation. As far as I understand it, every Livox user is constrained to only use the Livox-Viewer application to perform firmware updates.
-Ryan

**Comment by mikeszabi** [comment]
Bad news, but really thanks for the quick response!
Bests,
Mike
